task:
  name: Test
  container:
    image: golang:latest
  env:
    GOPROXY: https://proxy.golang.org
    GO111MODULE: on
  modules_cache:
    folder: $GOPATH/pkg/mod
    fingerprint_script: cat go.sum
    reupload_on_changes: false
  build_script: go build -v ./...
  windows_build_script: GOOS=windows go build -v ./...
  test_script: go test -v ./...


task:
  name: Lint
  container:
    image: golangci/golangci-lint:latest
  run_script:
    golangci-lint run
      -D errcheck
      -E stylecheck
      -E goimports
      -E misspell
      -E golint
      --exclude-use-default=false
      --max-same-issues=0
      --max-issues-per-linter=0
      --out-format json > lint-report.json
  always:
    golangci_artifacts:
      path: lint-report.json
      type: text/json
      format: golangci
